// web/src/routes/settings/security/+page.svelte
<script lang="ts">
	import { del, get, patch, post } from '#lib/api.ts';
	import { Guard } from '#lib/guard.svelte.ts';
	import { passkeysSupported, register } from '#lib/passkey.ts';
	import RecoveryCodes from '#lib/RecoveryCodes.svelte';
	import { loadMe, session } from '#lib/session.svelte.ts';
	import StepUp from '#lib/StepUp.svelte';

	type SessionInfo = { id: number; created_at: string; last_seen_at: string; user_agent: string | null; ip: string | null; current: boolean };

	const g = new Guard();
	let sessions = $state<SessionInfo[]>([]);
	let newPasskey = $state('');
	let totpSetup = $state<null | { ceremony: string; qr_svg: string; secret: string }>(null);
	let totpCode = $state('');
	let codes = $state<string[] | null>(null);
	let newPassword = $state('');
	let notice = $state('');

	const fmt = (s: string | null) => (s ? new Date(s).toLocaleString('de-DE') : '–');
	const refresh = async () => {
		await loadMe();
		sessions = await get<SessionInfo[]>('/me/sessions');
	};
	$effect(() => {
		refresh();
	});

	const addPasskey = () =>
		g.run(async () => {
			const begin = await post<{ ceremony: string; options: { publicKey: Record<string, unknown> } }>(
				'/me/passkeys/begin',
				{ name: newPasskey || 'Passkey' }
			);
			const credential = await register(begin.options);
			await post('/me/passkeys/finish', { ceremony: begin.ceremony, credential });
			newPasskey = '';
			notice = 'Passkey hinzugefügt.';
			await refresh();
		});

	const renamePasskey = (id: number, current: string) =>
		g.run(async () => {
			const name = prompt('Neuer Name', current);
			if (!name) return;
			await patch(`/me/passkeys/${id}`, { name });
			await refresh();
		});

	const removePasskey = (id: number) =>
		g.run(async () => {
			if (!confirm('Diesen Passkey entfernen?')) return;
			await del(`/me/passkeys/${id}`);
			await refresh();
		});

	const beginTotp = () =>
		g.run(async () => {
			totpSetup = await post('/me/totp/begin');
		});

	const confirmTotp = (e: SubmitEvent) => {
		e.preventDefault();
		g.run(async () => {
			await post('/me/totp/confirm', { ceremony: totpSetup?.ceremony, code: totpCode });
			totpSetup = null;
			totpCode = '';
			notice = 'Authenticator-App eingerichtet.';
			await refresh();
		});
	};

	const removeTotp = () =>
		g.run(async () => {
			if (!confirm('Authenticator-App entfernen?')) return;
			await del('/me/totp');
			await refresh();
		});

	const newCodes = () =>
		g.run(async () => {
			if (!confirm('Neue Codes erzeugen? Die alten werden ungültig.')) return;
			codes = (await post<{ recovery_codes: string[] }>('/me/recovery-codes')).recovery_codes;
		});

	const changePassword = (e: SubmitEvent) => {
		e.preventDefault();
		g.run(async () => {
			await post('/me/password', { password: newPassword });
			newPassword = '';
			notice = 'Passwort geändert. Andere Sitzungen wurden beendet.';
			await refresh();
		});
	};

	const revoke = (id: number) =>
		g.run(async () => {
			await del(`/me/sessions/${id}`);
			await refresh();
		});
</script>

<main class="page">
	<h1>Sicherheit</h1>
	{#if notice}<p class="ok">{notice}</p>{/if}
	{#if g.error}<p class="error" role="alert">{g.error}</p>{/if}

	{#if codes}
		<div class="card"><RecoveryCodes {codes} ondone={() => { codes = null; refresh(); }} /></div>
	{:else if session.me}
		<div class="card">
			<h2 style="margin-top: 0">Passkeys</h2>
			{#if session.me.passkeys.length}
				<table>
					<thead><tr><th>Name</th><th>Hinzugefügt</th><th>Zuletzt benutzt</th><th></th></tr></thead>
					<tbody>
						{#each session.me.passkeys as pk (pk.id)}
							<tr>
								<td>{pk.name}</td>
								<td>{fmt(pk.created_at)}</td>
								<td>{fmt(pk.last_used_at)}</td>
								<td class="row">
									<button onclick={() => renamePasskey(pk.id, pk.name)}>Umbenennen</button>
									<button class="danger" onclick={() => removePasskey(pk.id)}>Entfernen</button>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			{:else}
				<p class="muted">Noch kein Passkey. Mit Passkeys meldest du dich per Face ID oder Touch ID an.</p>
			{/if}
			{#if passkeysSupported()}
				<div class="row" style="margin-top: 1rem">
					<input placeholder="Name, z.B. MacBook" bind:value={newPasskey} style="max-width: 16rem" />
					<button class="primary" onclick={addPasskey} disabled={g.busy}>Passkey hinzufügen</button>
				</div>
			{/if}

			<h2>Authenticator-App</h2>
			{#if totpSetup}
				<p>Den QR-Code scannen und den angezeigten Code eingeben.</p>
				<div class="qr">{@html totpSetup.qr_svg}</div>
				<p class="muted">Schlüssel: <span class="code">{totpSetup.secret}</span></p>
				<form class="row" onsubmit={confirmTotp}>
					<input class="code" inputmode="numeric" autocomplete="one-time-code" bind:value={totpCode} required style="max-width: 10rem" />
					<button class="primary" disabled={g.busy}>Bestätigen</button>
					<button type="button" onclick={() => (totpSetup = null)}>Abbrechen</button>
				</form>
			{:else if session.me.totp}
				<p class="row">Eingerichtet. <button onclick={beginTotp}>Neu einrichten</button> <button class="danger" onclick={removeTotp}>Entfernen</button></p>
			{:else}
				<p class="row">Nicht eingerichtet. <button onclick={beginTotp}>Einrichten</button></p>
			{/if}

			<h2>Wiederherstellungscodes</h2>
			<p class="row">
				Noch {session.me.recovery_codes_left} von 10 übrig.
				<button onclick={newCodes}>Neue erzeugen</button>
			</p>

			<h2>Passwort</h2>
			<form class="row" onsubmit={changePassword}>
				<input type="password" autocomplete="new-password" minlength="12" placeholder="Neues Passwort" bind:value={newPassword} required style="max-width: 20rem" />
				<button disabled={g.busy}>Ändern</button>
			</form>
		</div>

		<div class="card" style="margin-top: 1.5rem">
			<h2 style="margin-top: 0">Angemeldete Sitzungen</h2>
			<table>
				<thead><tr><th>Gerät</th><th>IP</th><th>Zuletzt aktiv</th><th></th></tr></thead>
				<tbody>
					{#each sessions as s (s.id)}
						<tr>
							<td>{s.user_agent ?? 'unbekannt'} {#if s.current}<span class="badge">diese</span>{/if}</td>
							<td>{s.ip ?? '–'}</td>
							<td>{fmt(s.last_seen_at)}</td>
							<td>{#if !s.current}<button class="danger" onclick={() => revoke(s.id)}>Abmelden</button>{/if}</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</main>

{#if g.pending}<StepUp ondone={g.confirmed} oncancel={g.cancel} />{/if}

// web/app/pages/settings/security.vue
<script setup lang="ts">
type SessionInfo = {
	id: number;
	created_at: string;
	last_seen_at: string;
	user_agent: string | null;
	ip: string | null;
	current: boolean;
};

const { me, load } = useSession();
const g = useGuard();
const sessions = ref<SessionInfo[]>([]);
const newPasskey = ref('');
const totpSetup = ref<null | { ceremony: string; qr_svg: string; secret: string }>(null);
const totpCode = ref('');
const codes = ref<string[] | null>(null);
const newPassword = ref('');
const notice = ref('');
const canPasskey = ref(false);

async function refresh() {
	await load();
	sessions.value = await apiGet<SessionInfo[]>('/me/sessions');
}
onMounted(() => {
	canPasskey.value = passkeysSupported();
	g.run(refresh);
});

const addPasskey = () =>
	g.run(async () => {
		const begin = await apiPost<PasskeyBegin>('/me/passkeys/begin', {
			name: newPasskey.value || 'Passkey'
		});
		const credential = await registerPasskey(begin.options);
		await apiPost('/me/passkeys/finish', { ceremony: begin.ceremony, credential });
		newPasskey.value = '';
		notice.value = 'Passkey hinzugefügt.';
		await refresh();
	});

const renamePasskey = (id: number, current: string) =>
	g.run(async () => {
		const name = prompt('Neuer Name', current);
		if (!name) return;
		await apiPatch(`/me/passkeys/${id}`, { name });
		await refresh();
	});

const removePasskey = (id: number) =>
	g.run(async () => {
		if (!confirm('Diesen Passkey entfernen?')) return;
		await apiDelete(`/me/passkeys/${id}`);
		await refresh();
	});

const beginTotp = () =>
	g.run(async () => {
		totpSetup.value = await apiPost('/me/totp/begin');
	});

const confirmTotp = () =>
	g.run(async () => {
		await apiPost('/me/totp/confirm', { ceremony: totpSetup.value?.ceremony, code: totpCode.value });
		totpSetup.value = null;
		totpCode.value = '';
		notice.value = 'Authenticator-App eingerichtet.';
		await refresh();
	});

const removeTotp = () =>
	g.run(async () => {
		if (!confirm('Authenticator-App entfernen?')) return;
		await apiDelete('/me/totp');
		await refresh();
	});

const newCodes = () =>
	g.run(async () => {
		if (!confirm('Neue Codes erzeugen? Die alten werden ungültig.')) return;
		codes.value = (await apiPost<{ recovery_codes: string[] }>('/me/recovery-codes')).recovery_codes;
	});

const changePassword = () =>
	g.run(async () => {
		await apiPost('/me/password', { password: newPassword.value });
		newPassword.value = '';
		notice.value = 'Passwort geändert. Andere Sitzungen wurden beendet.';
		await refresh();
	});

const revoke = (id: number) =>
	g.run(async () => {
		await apiDelete(`/me/sessions/${id}`);
		await refresh();
	});

function codesDone() {
	codes.value = null;
	g.run(refresh);
}
</script>

<template>
	<main class="page">
		<h1>Sicherheit</h1>
		<p v-if="notice" class="ok">{{ notice }}</p>
		<p v-if="g.error.value" class="error" role="alert">{{ g.error.value }}</p>

		<div v-if="codes" class="card"><RecoveryCodes :codes="codes" @done="codesDone" /></div>
		<template v-else-if="me">
			<div class="card">
				<h2 style="margin-top: 0">Passkeys</h2>
				<table v-if="me.passkeys.length">
					<thead>
						<tr><th>Name</th><th>Hinzugefügt</th><th>Zuletzt benutzt</th><th></th></tr>
					</thead>
					<tbody>
						<tr v-for="pk in me.passkeys" :key="pk.id">
							<td>{{ pk.name }}</td>
							<td>{{ formatDate(pk.created_at) }}</td>
							<td>{{ formatDate(pk.last_used_at) }}</td>
							<td class="row">
								<button @click="renamePasskey(pk.id, pk.name)">Umbenennen</button>
								<button class="danger" @click="removePasskey(pk.id)">Entfernen</button>
							</td>
						</tr>
					</tbody>
				</table>
				<p v-else class="muted">
					Noch kein Passkey. Mit Passkeys meldest du dich per Face ID oder Touch ID an.
				</p>
				<div v-if="canPasskey" class="row" style="margin-top: 1rem">
					<input v-model="newPasskey" placeholder="Name, z.B. MacBook" style="max-width: 16rem" />
					<button class="primary" :disabled="g.busy.value" @click="addPasskey">Passkey hinzufügen</button>
				</div>

				<h2>Authenticator-App</h2>
				<template v-if="totpSetup">
					<p>Den QR-Code scannen und den angezeigten Code eingeben.</p>
					<!-- SVG generated by the server; contains no user input as markup. -->
					<div class="qr" v-html="totpSetup.qr_svg"></div>
					<p class="muted">Schlüssel: <span class="code">{{ totpSetup.secret }}</span></p>
					<form class="row" @submit.prevent="confirmTotp">
						<input
							v-model="totpCode"
							class="code"
							inputmode="numeric"
							autocomplete="one-time-code"
							required
							style="max-width: 10rem"
						/>
						<button class="primary" :disabled="g.busy.value">Bestätigen</button>
						<button type="button" @click="totpSetup = null">Abbrechen</button>
					</form>
				</template>
				<p v-else-if="me.totp" class="row">
					Eingerichtet. <button @click="beginTotp">Neu einrichten</button>
					<button class="danger" @click="removeTotp">Entfernen</button>
				</p>
				<p v-else class="row">Nicht eingerichtet. <button @click="beginTotp">Einrichten</button></p>

				<h2>Wiederherstellungscodes</h2>
				<p class="row">
					Noch {{ me.recovery_codes_left }} von 10 übrig.
					<button @click="newCodes">Neue erzeugen</button>
				</p>

				<h2>Passwort</h2>
				<form class="row" @submit.prevent="changePassword">
					<input
						v-model="newPassword"
						type="password"
						autocomplete="new-password"
						minlength="12"
						placeholder="Neues Passwort"
						required
						style="max-width: 20rem"
					/>
					<button :disabled="g.busy.value">Ändern</button>
				</form>
			</div>

			<div class="card" style="margin-top: 1.5rem">
				<h2 style="margin-top: 0">Angemeldete Sitzungen</h2>
				<table>
					<thead>
						<tr><th>Gerät</th><th>IP</th><th>Zuletzt aktiv</th><th></th></tr>
					</thead>
					<tbody>
						<tr v-for="s in sessions" :key="s.id">
							<td>
								{{ s.user_agent ?? 'unbekannt' }}
								<span v-if="s.current" class="badge">diese</span>
							</td>
							<td>{{ s.ip ?? '–' }}</td>
							<td>{{ formatDate(s.last_seen_at) }}</td>
							<td>
								<button v-if="!s.current" class="danger" @click="revoke(s.id)">Abmelden</button>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</template>
	</main>
	<StepUpDialog v-if="g.pending.value" @done="g.confirmed" @cancel="g.cancel" />
</template>
